### ISSUE TITLE
Pruebas funcionales y Unitarias - Fase 1

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_mid_v2#13]
Se debe registrar el resultado de las pruebas funcionales y unitarias, asociadas a los modulos implementados a la fecha (Plantillas y Gestión de Resoluciones).

**Criterios de aceptación**

- [x] Documento que evidencie la realizacion de pruebas funcionales en el sistema.
- [x] Documento que evidencie la realización de pruebas unitarias en el sistema.
- [x] Commit asociado a pruebas unitarias.

**Comment by jupmorenor** [comment]
Se ajustaron los ficheros de pruebas unitarias que se generan automáticamente al crear componentes en Angular para que las pruebas en el cliente pasen satisfactoriamente:
![image](https://user-images.githubusercontent.com/11802554/149410492-136fb9ed-e9c8-4695-bf84-62fe148a5573.png)

**Comment by jupmorenor** [comment]
Se generan pruebas unitarias en API MID
![image](https://user-images.githubusercontent.com/11802554/149557815-4668da2e-cd79-44d0-b85a-9195bdfa77aa.png)

**Comment by jupmorenor** [comment]
Se generan pruebas de API CRUD
![image](https://user-images.githubusercontent.com/11802554/149603144-4587d3d3-2fa8-4b9b-b55f-26bccd80e0d1.png)

**Comment by jupmorenor** [comment]
Se realizaron pruebas funcionales sobre las funcionalidades desarrolladas hasta el momento así:

1. Modulo de plantillas:

> - Creación de plantillas
> - Cargue del contenido y actualización de plantillas
> - Listado de plantillas
> - Eliminación de plantillas

2. Modulo de gestión de resoluciones

> - Listado de resoluciones general
> - Generación de resoluciones (usando la plantilla según el tipo)
> - cargue del contenido y edición de resolución
> - Listado de resoluciones expedidas para crear modificación
> - Consulta por documento del docente

En el siguiente documento se han registrado los hallazgos: [click aqui](https://docs.google.com/spreadsheets/d/1y_WKMaifV68991y1M_za9SfylJpU53ie/edit?usp=sharing&ouid=115705338596905688240&rtpof=true&sd=true)

**Comment by jupmorenor** [comment]
Se realizó la corrección de los hallazgos de las pruebas funcionales.

**Comment by a52290451** [comment]
Se validan pruebas Unitarias y funcionales realizadas a la fecha.
