### ISSUE TITLE
Correccion de prima de servicios en cancelaciones 

### ISSUE THREAD

**Issue by aalejoz25** [udistrital/resoluciones_mid_v2#194]
Se tiene el caso, que para calcular el desagregado de un contrato al hacer una cancelacion, no se tiene en cuenta el tipo de resolucion al momento de pasar el numero de semanas en el calculo del desagregado. Por esta razon el valor a cancelar daba 0. Para ello, se realizo una correccion en el endpoint de titan desagregado_hcs Para tener en cuenta dicho caso: 

[https://github.com/udistrital/titan_api_mid/pull/497](https://github.com/udistrital/titan_api_mid/pull/497 )

 Ahora, se propone pasar como parametro el tipo de resolucion para que dicho endpoint calcule adecuadamente los valores de la prima de servicios.

**Comment by criss201x** [comment]
Por favor linkear iris o kb del incidente mencionado, se mantiene abierto el Issue hasta que haya confirmación por parte del usuario
