### ISSUE TITLE
Pruebas unitarias

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_mid_v2#49]
Se debe registrar el resultado de las pruebas unitarias asociadas a las unidades de código implementadas hasta el momento que no cuenten con estas.

- [x] Documento o comentario que evidencie la realización de pruebas unitarias en el sistema.

**Comment by jupmorenor** [comment]
- Se hizo revisión de pruebas unitarias en [API MID](https://github.com/udistrital/resoluciones_mid_v2) y se realizaron los ajustes pertinentes teniendo en cuenta los cambios realizados desde la ultima vez que se revisaron.
- Se hizo revisión de pruebas unitarias en [API CRUD](https://github.com/udistrital/resoluciones_crud_v2), no se requiere realizar ajustes.
