### ISSUE TITLE
Corregir comportamiento de cancelaciones

### ISSUE THREAD

**Issue by milo19980525** [udistrital/resoluciones_mid_v2#59]
Corregir el comportamiento de la resolución de cancelación en:

- [x] Contrato inicial + adición.
- [x] Contrato inicial + reducción.

**Comment by jupmorenor** [comment]
Se realiza análisis de los dos escenarios especiales planteados para esta oportunidad:
- Si existe una reducción se procede de la misma manera que con una vinculación.
- Si existe una adición se deben cancelar tanto la adición como la vinculación, ya que estas tienen diferente DVE y RP

Documento de análisis: [link](https://docs.google.com/spreadsheets/d/10JQKR6abBLywuwdkSvst8UCWxcbu8axaaMLLAhx79Hg/edit#gid=1004228386)
