### ISSUE TITLE
Creación de Mock-ups para el módulo de gestión de resoluciones

### ISSUE THREAD

**Issue by a52290451** [udistrital/resoluciones_mid_v2#9]
Realizar la implementación de los Mock-Ups asociados al modulo de gestión de resoluciones para el nuevo Resoluciones.

**Criterio de aceptación**

- [ ] Mock-ups asociados al modulo de gestión de resoluciones.

**Comment by Yaov05** [comment]
Se elaboran mockups para el nuevo sistema de resoluciones relacionados al módulo de gestión de resoluciones:

1. Listado de resoluciones

![1](https://user-images.githubusercontent.com/42217637/146374358-6a72e838-89fb-427e-a312-bc75543ba669.PNG)

2. Generación de resolución de vinculación

![Generacion](https://user-images.githubusercontent.com/42217637/146374437-5fd2a11e-0852-4691-930f-75c625f969fb.PNG)

3. Generación de resolución de cancelación
![Generacion 2](https://user-images.githubusercontent.com/42217637/146374494-da51b9f3-bc59-4359-a9e5-429e7a3fa897.PNG)

4. Consulta de docentes
![consultar](https://user-images.githubusercontent.com/42217637/146374532-9a920a5f-93de-4899-a925-0163e12b04e7.PNG)

Los mockups se están trabajando en el siguiente [documento](https://drive.google.com/file/d/1ofrrnEnqXmkz5t7MIMXPkabTavHRmK1i/view) (draw.io)

**Comment by a52290451** [comment]
Se realiza la revisión de Mock-Ups, con las siguientes observaciones:

1. Para la vista de consulta de docentes, se requiere mostrar las resoluciones filtradas en una tabla, con la opción de visualizar su contenido.
2. Para complementar el diseño, seguir las recomendaciones realizadas en: (https://github.com/udistrital/resoluciones_docentes_crud/issues/10)

**Comment by Yaov05** [comment]
Se adjuntan los mock-ups correspondientes al módulo de expedición de la resolución y la visualización de resoluciones.
![Visualización1](https://user-images.githubusercontent.com/42217637/149772975-6c3640b7-7817-4221-9400-562c711a8dde.PNG)
![Visualización2](https://user-images.githubusercontent.com/42217637/149772992-4c28c354-d78d-436a-8808-c8dca3410c18.PNG)

![Exp1](https://user-images.githubusercontent.com/42217637/149773000-00918ff7-b11f-4b39-ab5f-1b1291b64fd7.PNG)

![Exp2](https://user-images.githubusercontent.com/42217637/149773010-58808f39-60af-43ba-9ef3-549ed63963da.PNG)

![Exp3](https://user-images.githubusercontent.com/42217637/149773018-938fb00d-cc23-4477-88f7-cea451f2882d.PNG)
